replicaCount: 3
image:
  user: 0770asd
  repository: hello-kube
  pullPolicy: IfNotPresent
  tag: 20841c8
commonLabels:
  app.kubernetes.io/name: hello-kube
  app.kubernetes.io/instance: hello-kube-test
  app.kubernetes.io/version:
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: k8s-khw-project-01
  app.kubernetes.io/managed-by: argoCD
  app.kubernetes.io/created-by: manual
podLabels: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: hello-kube.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
    - name: gateway
      sectionName: http
      # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
    - chart-example.local
  # List of rules and filters applied.
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
            #   filters:
            #   - type: RequestHeaderModifier
            #     requestHeaderModifier:
            #       set:
            #       - name: My-Overwrite-Header
            #         value: this-is-the-only-value
            #       remove:
            #       - User-Agent
            # - matches:
            #   - path:
            #       type: PathPrefix
            #       value: /echo
            #     headers:
            #     - name: version
            #       value: v2
# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
