apiVersion: v1
kind: ConfigMap  # Pod의 환경변수 값을 제공
metadata:
  namespace: k8s-khw-ns-01
  name: hello-kube-01-properties
  labels:
    {{ .Values.commonLabels . | indent 4 }}
data:  # 환경변수 값
  test_env_value: "hello-kube"
---
apiVersion: v1
kind: Secret  # Pod에게 더 중요한 값을 제공하는데 사용
metadata:
  namespace: k8s-khw-ns-01
  name: hello-kube-01-postgresql
  labels:
    {{ .Values.commonLabels . | indent 4 }}
stringData:  # 해당 옵션 값은 Pod내에 파일을 생성하는 값임
  postgresql-info.yaml: |  # postgresql-info.yaml 파일에 아래의 내용을 채워넣은 파일이 생성됨
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "test"
    password: "test123"