apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kube
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/GG2S/k8s-khw-manifest.git
    targetRevision: main
    path: hello-kube
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-khw-ns-01

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      