apiVersion: v1
kind: Service
metadata:  # metadata는 Object 별로 다 있음
  namespace: k8s-khw-ns-01
  name: hello-kube-01-svc
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:  # 연결 정보 속성
  selector:
    {{- index .Values.commonLabels "app.kubernetes.io/name" | nindent 4 }}
    {{- index .Values.commonLabels "app.kubernetes.io/instance" | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
      # nodePort: 31231   type이 NodePort일 때 사용
  type: ClusterIP  # Ingress 사용할거기 때문에 NodePort -> ClusterIP로 변경