apiVersion: v1
kind: Service
metadata:  # metadata는 Object 별로 다 있음
  namespace: k8s-khw-ns-01
  name: hello-kube-01-svc
  labels:
    {{ include "hello-kube.labels" . | indent 4 }}
spec:  # 연결 정보 속성
  selector:
    {{ include "hello-kube.selectorLabels" . | indent 4 }}
    - port: 80
      targetPort: http
      # nodePort: 31231   type이 NodePort일 때 사용
  type: ClusterIP  # Ingress 사용할거기 때문에 NodePort -> ClusterIP로 변경